"use client";

import React, { useState } from "react";
import Link from "next/link";
import UserNavbar from "@/components/UserNavbar";
import Footer from "@/components/Footer";
import {
  Bell,
  Search,
  Filter,
  ArrowLeft,
  Calendar,
  FileText,
  Download,
  ExternalLink,
  ShieldCheck,
  AlertCircle,
  Tag,
  CheckCheck,
} from "lucide-react";

interface NoticeItem {
  id: number;
  title: string;
  category: "Advisory" | "Security" | "Compliance" | "Maintenance" | "Circular";
  date: string;
  unread: boolean;
  refNo?: string;
  content: string;
}

const allNotices: NoticeItem[] = [
  {
    id: 1,
    title: "Advisory on GSTR-1 / IFF filing for July 2026",
    category: "Advisory",
    date: "22-Aug-2026",
    unread: true,
    refNo: "GSTN/ADV/2026/08/104",
    content:
      "Taxpayers opting for the Quarterly Return Monthly Payment (QRMP) Scheme are advised to file their Invoice Furnishing Facility (IFF) for July 2026 before the deadline. Ensure all B2B invoices and credit/debit notes are reported accurately.",
  },
  {
    id: 2,
    title: "Enhanced security: Mandatory 2-Factor Authentication (2FA) active",
    category: "Security",
    date: "18-Aug-2026",
    unread: true,
    refNo: "GSTN/SEC/2026/08/92",
    content:
      "To prevent unauthorized access and tax frauds, 2-Factor Authentication (2FA) is made mandatory for all regular taxpayers. OTP verification on registered mobile and email or Authenticator App is required at login.",
  },
  {
    id: 3,
    title: "Advisory on IMS (Invoice Management System) for ITC reconciliation",
    category: "Compliance",
    date: "14-Aug-2026",
    unread: false,
    refNo: "GSTN/IMS/2026/08/78",
    content:
      "The newly introduced Invoice Management System (IMS) enables recipient taxpayers to seamlessly accept, reject, or keep pending invoices uploaded by suppliers in GSTR-1/IFF, facilitating auto-population into GSTR-2B.",
  },
  {
    id: 4,
    title: "System Maintenance window scheduled on 28th Aug 2026 (01:00 AM - 04:00 AM)",
    category: "Maintenance",
    date: "10-Aug-2026",
    unread: false,
    refNo: "GSTN/MAINT/2026/08/45",
    content:
      "Scheduled server upgrade and infrastructure maintenance will take place on Sunday, 28th August 2026 between 01:00 AM and 04:00 AM IST. Portal services may experience brief intermittent downtime.",
  },
  {
    id: 5,
    title: "Clarification on HSN Code requirement for B2B electronic invoices",
    category: "Circular",
    date: "05-Aug-2026",
    unread: false,
    refNo: "CBIC/CIR/2026/184/08",
    content:
      "Central Board of Indirect Taxes & Customs clarifies that 6-digit HSN codes are compulsory on all e-invoices and tax invoices issued by registered persons having aggregate turnover exceeding ₹5 Crore in preceding financial year.",
  },
  {
    id: 6,
    title: "Procedure for filing GST Refund application (Form RFD-01) for inverted duty structure",
    category: "Advisory",
    date: "28-Jul-2026",
    unread: false,
    refNo: "GSTN/REF/2026/07/31",
    content:
      "Step-by-step guidance on submitting Statement 1A along with calculation sheets and certificates for claiming accumulated ITC refund under inverted duty structure.",
  },
  {
    id: 7,
    title: "Advisory on Geocoding of Principal and Additional Places of Business",
    category: "Compliance",
    date: "20-Jul-2026",
    unread: false,
    refNo: "GSTN/GEO/2026/07/19",
    content:
      "All taxpayers who have not geocoded their principal place of business are encouraged to accept or edit the geocoded address generated by the system under Services > Registration > Geocoding.",
  },
  {
    id: 8,
    title: "Advisory on Special Drive against fake registrations and fraudulent ITC claims",
    category: "Circular",
    date: "12-Jul-2026",
    unread: false,
    refNo: "CBIC/ADV/2026/07/04",
    content:
      "State and Central tax administrations have launched a joint national verification drive to verify high-risk non-compliant entities. Genuine taxpayers are requested to ensure business name boards and GSTIN are displayed at their registered premises.",
  },
];

export default function NotificationsPage() {
  const [searchTerm, setSearchTerm] = useState("");
  const [activeCategory, setActiveCategory] = useState<string>("All");

  const categories = ["All", "Advisory", "Security", "Compliance", "Maintenance", "Circular"];

  const filteredNotices = allNotices.filter((n) => {
    const matchesCategory = activeCategory === "All" || n.category === activeCategory;
    const matchesSearch =
      n.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      n.content.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (n.refNo && n.refNo.toLowerCase().includes(searchTerm.toLowerCase()));
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="min-h-screen flex flex-col bg-[#f4f7fb]">
      {/* Navbar */}
      <UserNavbar />

      {/* Main Content */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        {/* Top Breadcrumb & Actions */}
        <div className="mb-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200/80 pb-4">
          <div className="space-y-1">
            <Link
              href="/userPage"
              className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#0284c7] hover:underline"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span>Back to Dashboard</span>
            </Link>
            <h1 className="text-2xl font-black text-[#072a5e] flex items-center gap-2.5">
              <Bell className="w-6 h-6 text-[#0284c7]" />
              <span>All Notices &amp; Circular Updates</span>
            </h1>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-500 bg-white px-3 py-1.5 rounded-xl border border-slate-200 shadow-xs">
              Showing <strong className="text-[#072a5e]">{filteredNotices.length}</strong> Notifications
            </span>
          </div>
        </div>

        {/* Search & Category Filter Bar */}
        <div className="bg-white rounded-2xl p-4 sm:p-5 border border-slate-200/90 shadow-sm space-y-4 mb-6">
          <div className="flex flex-col md:flex-row items-center gap-4">
            
            {/* Search Input */}
            <div className="relative flex-1 w-full">
              <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search advisories, notifications, circulars by keyword or reference ID..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full bg-[#f8fafc] border border-slate-200 rounded-xl pl-10 pr-4 py-2 text-xs sm:text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-[#0284c7]/40 focus:border-[#0284c7]"
              />
            </div>

            {/* Category Pills */}
            <div className="flex items-center gap-1.5 overflow-x-auto w-full md:w-auto pb-1 md:pb-0">
              {categories.map((cat) => (
                <button
                  key={cat}
                  type="button"
                  onClick={() => setActiveCategory(cat)}
                  className={`whitespace-nowrap px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                    activeCategory === cat
                      ? "bg-[#072a5e] text-white shadow-xs"
                      : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>

          </div>
        </div>

        {/* Notices Listing */}
        <div className="space-y-4">
          {filteredNotices.length > 0 ? (
            filteredNotices.map((notice) => (
              <div
                key={notice.id}
                className="bg-white rounded-2xl p-5 sm:p-6 border border-slate-200/90 shadow-sm hover:shadow-md hover:border-[#85b6ee] transition-all space-y-3 relative group"
              >
                {notice.unread && (
                  <span className="absolute top-4 right-4 inline-flex items-center gap-1 text-[10px] font-bold text-rose-700 bg-rose-50 border border-rose-200 px-2.5 py-0.5 rounded-full">
                    <span className="w-1.5 h-1.5 rounded-full bg-rose-500 animate-pulse" />
                    New
                  </span>
                )}

                <div className="flex flex-wrap items-center gap-2">
                  <span className="text-[11px] font-bold px-2.5 py-0.5 rounded-md bg-[#eef6fc] text-[#0284c7] border border-[#85b6ee]/50">
                    {notice.category}
                  </span>
                  {notice.refNo && (
                    <span className="text-[11px] font-mono text-slate-400">
                      Ref: {notice.refNo}
                    </span>
                  )}
                  <span className="text-slate-300">•</span>
                  <span className="text-[11px] text-slate-400 flex items-center gap-1">
                    <Calendar className="w-3 h-3" />
                    {notice.date}
                  </span>
                </div>

                <h3 className="text-base sm:text-lg font-bold text-[#072a5e] group-hover:text-[#0284c7] transition-colors leading-snug">
                  {notice.title}
                </h3>

                <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
                  {notice.content}
                </p>

                <div className="pt-2 border-t border-slate-100 flex items-center justify-between gap-4">
                  <div className="flex items-center gap-2 text-xs text-slate-400">
                    <ShieldCheck className="w-3.5 h-3.5 text-emerald-500" />
                    <span>Issued by GSTN / CBIC Official Desk</span>
                  </div>

                  <button
                    type="button"
                    onClick={() => alert(`Downloading notice document: ${notice.title}`)}
                    className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#0284c7] hover:text-[#072a5e] hover:underline"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download Circular</span>
                  </button>
                </div>

              </div>
            ))
          ) : (
            <div className="bg-white rounded-2xl p-12 text-center border border-slate-200 shadow-sm space-y-3">
              <AlertCircle className="w-10 h-10 text-slate-300 mx-auto" />
              <h4 className="text-base font-bold text-slate-700">No notices matched your filter</h4>
              <p className="text-xs text-slate-400">Try changing your search terms or category filter.</p>
            </div>
          )}
        </div>

      </main>

      {/* Footer */}
      <Footer />
    </div>
  );
}
